CLASSPATH1 = "C:\\Program Files\\Java\\jdk1.8.0_171\\bin\\javac"
CLASSPATH2 = "C:\\Program Files\\Java\\jdk1.8.0_171\\bin\\java"
UPLOAD_FILES_PATH = "G:\\Romu\\PythonOnWeb"
FILE_STORE_PATH = "G:\\Romu\\PythonOnWeb\\"
ACCESS_KEY = ""
SECRET_KEY = ""
